main: me.beezle.hats.Hats
version: 2.0.1
name: Hats
author: Beezle
website: https://github.com/AleksandarHaralanov
description: Players can wear blocks as hats.

commands:
  hat:
    description: Set the block in hand as a hat.
    permission: hats.wear
    permission-message: You do not have permissions to wear hats.
    usage: /<command> [version]

permissions:
    hats.wear:
      description: Allows the player to wear blocks as hats.
      default: op