main: me.beezle.hats.Hats
version: 1.0.1
name: Hats
authors: [Beezle]
description: Players can wear blocks and items as hats.

commands:
  hat:
    description: Set the item in hand as a hat.
    permission: hats.wear
    permission-message: You do not have permissions to wear hats.
    usage: /<command>

permissions:
    hats.wear:
      description: Allows the player to wear blocks and items as hats.
      default: op