main: com.haralanov.hats.Hats
version: 3.1.1
name: Hats
author: Beezle
website: https://github.com/AleksandarHaralanov/Hats
description: Players can wear blocks as hats.

commands:
  hat:
    description: Set the block in hand as a hat.
    usage: /<command>
  hats:
    description: Check information about Hats plugin.
    usage: /<command>

permissions:
    hats.wear:
      description: Allows the player to wear blocks as hats.
      default: op