main: io.github.aleksandarharalanov.hats.Hats
version: 4.1.0-rc.2
name: Hats
author: Beezle
website: github.com/AleksandarHaralanov/Hats
description: Players can wear blocks as hats and some emit dynamic light.

commands:
  hat:
    description: All of Hats' features in one command.
    usage: /hat [help]

permissions:
  hats.*:
    children:
      hats.wear: true
      hats.light: true
      hats.settings: true
    default: op
  hats.perks:
    children:
      hats.wear: true
      hats.light: true
      hats.settings: false
    default: op
  hats.wear:
    description: Allows the player to wear blocks as hats.
    default: op
  hats.light:
    description: Allows specific hats to emit light and be toggled by the player when worn.
    default: op
  hats.settings:
    description: Allows the player to reload and change the config.
    default: op