main: com.haralanov.hats.Hats
version: 3.1.5
name: Hats
author: Beezle
website: github.com/AleksandarHaralanov/Hats
description: Players can wear blocks as hats.

commands:
  hat:
    description: Wear the block in hand as a hat.
    usage: /<command>
  hats:
    description: See info about the Hats plugin.
    usage: /<command>

permissions:
    hats.wear:
      description: Allows the player to wear blocks as hats.
      default: op