main: com.haralanov.hats.Hats
version: 4.0.0
name: Hats
author: Beezle
website: github.com/AleksandarHaralanov/Hats
description: Players can wear blocks as hats.

commands:
  hat:
    description: Wear the block in hand as a hat.
    usage: /<command> [about]

permissions:
    hats.wear:
      description: Allows the player to wear blocks as hats.
      default: op