main: com.haralanov.hats.Hats
version: 2.3.0
name: Hats
author: AleksandarHaralanov
website: https://github.com/AleksandarHaralanov
description: Players can wear blocks as hats.

commands:
  hat:
    description: Set the block in hand as a hat.
    permission: hats.wear
    permission-message: You do not have permissions to wear hats.
    usage: /<command>
  hats:
    description: Check information about Hats plugin.
    usage: /<command>

permissions:
    hats.wear:
      description: Allows the player to wear blocks as hats.
      default: op