main: io.github.aleksandarharalanov.hats.Hats
version: 4.1.0-rc.2
name: Hats
author: Beezle
website: github.com/AleksandarHaralanov/Hats
description: Players can wear blocks as hats.

commands:
  hat:
    description: Use all Hats features in one command.
    usage: /hat [about | light | reload | settings]

permissions:
  hats.*:
    children:
      hats.wear: true
      hats.light: true
      hats.settings: true
    default: op
  hats.perks:
    children:
      hats.wear: true
      hats.light: true
      hats.settings: false
    default: op
  hats.wear:
    description: Allows the player to wear blocks as hats.
    default: op
  hats.light:
    description: Allows specific hats to emit light and be toggled by the player when worn.
    default: op
  hats.settings:
    description: Allows the player to view, reload, and modify the config.
    default: op